### ISSUE TITLE
IPv6 error

### ISSUE THREAD

**Issue by gbiagomba** [rverton/webanalyze#42]
Hello,

When i tried running a scan of an IPv6 address i got the following error every time
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x702474]

goroutine 34 [running]:
github.com/rverton/webanalyze.(*WebAnalyzer).Process(0xc00000e580, 0xc000051f58, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/ubuntu/go/src/github.com/rverton/webanalyze/webanalyze.go:75 +0x74
main.main.func1(0xc00001a120, 0xc000011390, 0xc000011398, 0xc000016330)
	/home/ubuntu/go/src/github.com/rverton/webanalyze/cmd/webanalyze/main.go:115 +0x36d
created by main.main
	/home/ubuntu/go/src/github.com/rverton/webanalyze/cmd/webanalyze/main.go:111 +0x3f2
```

**Comment by rverton** [comment]
I added a fix with eb56e98c8da33b16706662a53ee229ca82a370bc so the error message is more clear.

If you want to scan an IPv6 address, please use the proper format, for example:
`webanalyze -host "http://[2a02:2e0:3fe:1001:302::]"`
